cors:
  originPatterns: http://localhost:3000,http://localhost:8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/movies-api?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: gustavo
    password: tomate09
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**
  swagger-ui:
    use-root-path: true