server:
  port: 80
cors:
  originPatterns: http://localhost:3000,http://localhost:80800
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://resources-api.cykf6rrh7h0s.us-east-1.rds.amazonaws.com:3306/resources_api?useTimezone=true&serverTimezone=UTC
    username: docker
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/**
  swagger-ui:
    use-root-path: true
cloud:
  aws:
    stack:
      auto: false